### ISSUE TITLE
Errors at startup

### ISSUE THREAD

**Issue by rovale** [josecastroleon/pimatic-weather#9]
Hi,

When I (re)start pimatic, I get the following errors:

```
23:23:14.987 [pimatic] error: Could not get attribute value of Nu.status: err is not defined
23:23:15.442 [pimatic] debug: ReferenceError: err is not defined
23:23:15.442 [pimatic] debug:>    at /home/pi/weather.coffee:67:26
23:23:15.442 [pimatic] debug:>    at tryCatch1 (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:43:21)
23:23:15.442 [pimatic] debug:>    at Promise$_callHandler [as _callHandler] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:627:13)
23:23:15.442 [pimatic] debug:>    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:641:18)
23:23:15.442 [pimatic] debug:>    at Promise$_settlePromiseAt [as _settlePromiseAt] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:800:14)
23:23:15.442 [pimatic] debug:>    at Promise$_settlePromises [as _settlePromises] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:934:14)
23:23:15.442 [pimatic] debug:>    at Promise$_rejectPromises [as _rejectPromises] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:927:10)
23:23:15.442 [pimatic] debug:>    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:75:12)
23:23:15.442 [pimatic] debug:>    at Async$consumeFunctionBuffer (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:38:14)
23:23:15.442 [pimatic] debug:>    at process._tickCallback (node.js:415:13)
23:23:15.486 [pimatic] error: Could not get attribute value of Nu.windspeed: err is not defined
23:23:15.524 [pimatic] debug: ReferenceError: err is not defined
23:23:15.524 [pimatic] debug:>    at /home/pi/weather.coffee:67:26
23:23:15.524 [pimatic] debug:>    at tryCatch1 (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:43:21)
23:23:15.524 [pimatic] debug:>    at Promise$_callHandler [as _callHandler] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:627:13)
23:23:15.524 [pimatic] debug:>    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:641:18)
23:23:15.524 [pimatic] debug:>    at Promise$_settlePromiseAt [as _settlePromiseAt] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:800:14)
23:23:15.524 [pimatic] debug:>    at Promise$_settlePromises [as _settlePromises] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:934:14)
23:23:15.524 [pimatic] debug:>    at Promise$_rejectPromises [as _rejectPromises] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:927:10)
23:23:15.524 [pimatic] debug:>    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:75:12)
23:23:15.524 [pimatic] debug:>    at Async$consumeFunctionBuffer (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:38:14)
23:23:15.524 [pimatic] debug:>    at process._tickCallback (node.js:415:13)
23:23:15.568 [pimatic] error: Could not get attribute value of Nu.temperature: err is not defined
23:23:15.605 [pimatic] debug: ReferenceError: err is not defined
23:23:15.605 [pimatic] debug:>    at /home/pi/weather.coffee:67:26
23:23:15.605 [pimatic] debug:>    at tryCatch1 (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:43:21)
23:23:15.605 [pimatic] debug:>    at Promise$_callHandler [as _callHandler] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:627:13)
23:23:15.605 [pimatic] debug:>    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:641:18)
23:23:15.605 [pimatic] debug:>    at Promise$_settlePromiseAt [as _settlePromiseAt] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:800:14)
23:23:15.605 [pimatic] debug:>    at Promise$_settlePromises [as _settlePromises] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:934:14)
23:23:15.605 [pimatic] debug:>    at Promise$_rejectPromises [as _rejectPromises] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:927:10)
23:23:15.605 [pimatic] debug:>    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:75:12)
23:23:15.605 [pimatic] debug:>    at Async$consumeFunctionBuffer (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:38:14)
23:23:15.605 [pimatic] debug:>    at process._tickCallback (node.js:415:13)
23:23:15.649 [pimatic] error: Could not get attribute value of Nu.humidity: err is not defined
23:23:15.684 [pimatic] debug: ReferenceError: err is not defined
23:23:15.684 [pimatic] debug:>    at /home/pi/weather.coffee:67:26
23:23:15.684 [pimatic] debug:>    at tryCatch1 (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:43:21)
23:23:15.684 [pimatic] debug:>    at Promise$_callHandler [as _callHandler] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:627:13)
23:23:15.684 [pimatic] debug:>    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:641:18)
23:23:15.684 [pimatic] debug:>    at Promise$_settlePromiseAt [as _settlePromiseAt] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:800:14)
23:23:15.684 [pimatic] debug:>    at Promise$_settlePromises [as _settlePromises] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:934:14)
23:23:15.684 [pimatic] debug:>    at Promise$_rejectPromises [as _rejectPromises] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:927:10)
23:23:15.684 [pimatic] debug:>    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:75:12)
23:23:15.684 [pimatic] debug:>    at Async$consumeFunctionBuffer (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:38:14)
23:23:15.684 [pimatic] debug:>    at process._tickCallback (node.js:415:13)
23:23:15.731 [pimatic] error: Could not get attribute value of Voorspelling morgen.forecast: err is not defined
23:23:15.825 [pimatic] debug: ReferenceError: err is not defined
23:23:15.825 [pimatic] debug:>    at /home/pi/weather.coffee:120:26
23:23:15.825 [pimatic] debug:>    at tryCatch1 (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:43:21)
23:23:15.825 [pimatic] debug:>    at Promise$_callHandler [as _callHandler] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:627:13)
23:23:15.825 [pimatic] debug:>    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:641:18)
23:23:15.825 [pimatic] debug:>    at Promise$_settlePromiseAt [as _settlePromiseAt] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:800:14)
23:23:15.825 [pimatic] debug:>    at Promise$_settlePromises [as _settlePromises] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:934:14)
23:23:15.825 [pimatic] debug:>    at Promise$_rejectPromises [as _rejectPromises] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:927:10)
23:23:15.825 [pimatic] debug:>    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:75:12)
23:23:15.825 [pimatic] debug:>    at Async$consumeFunctionBuffer (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:38:14)
23:23:15.825 [pimatic] debug:>    at process._tickCallback (node.js:415:13)
23:23:15.870 [pimatic] error: Could not get attribute value of Voorspelling morgen.low: err is not defined
23:23:15.906 [pimatic] debug: ReferenceError: err is not defined
23:23:15.906 [pimatic] debug:>    at /home/pi/weather.coffee:120:26
23:23:15.906 [pimatic] debug:>    at tryCatch1 (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:43:21)
23:23:15.906 [pimatic] debug:>    at Promise$_callHandler [as _callHandler] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:627:13)
23:23:15.906 [pimatic] debug:>    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:641:18)
23:23:15.906 [pimatic] debug:>    at Promise$_settlePromiseAt [as _settlePromiseAt] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:800:14)
23:23:15.906 [pimatic] debug:>    at Promise$_settlePromises [as _settlePromises] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:934:14)
23:23:15.906 [pimatic] debug:>    at Promise$_rejectPromises [as _rejectPromises] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:927:10)
23:23:15.906 [pimatic] debug:>    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:75:12)
23:23:15.906 [pimatic] debug:>    at Async$consumeFunctionBuffer (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:38:14)
23:23:15.906 [pimatic] debug:>    at process._tickCallback (node.js:415:13)
23:23:15.951 [pimatic] error: Could not get attribute value of Voorspelling morgen.high: err is not defined
23:23:15.989 [pimatic] debug: ReferenceError: err is not defined
23:23:15.989 [pimatic] debug:>    at /home/pi/weather.coffee:120:26
23:23:15.989 [pimatic] debug:>    at tryCatch1 (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:43:21)
23:23:15.989 [pimatic] debug:>    at Promise$_callHandler [as _callHandler] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:627:13)
23:23:15.989 [pimatic] debug:>    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:641:18)
23:23:15.989 [pimatic] debug:>    at Promise$_settlePromiseAt [as _settlePromiseAt] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:800:14)
23:23:15.989 [pimatic] debug:>    at Promise$_settlePromises [as _settlePromises] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:934:14)
23:23:15.989 [pimatic] debug:>    at Promise$_rejectPromises [as _rejectPromises] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:927:10)
23:23:15.989 [pimatic] debug:>    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:75:12)
23:23:15.989 [pimatic] debug:>    at Async$consumeFunctionBuffer (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:38:14)
23:23:15.989 [pimatic] debug:>    at process._tickCallback (node.js:415:13)
23:23:16.033 [pimatic] error: Could not get attribute value of Voorspelling morgen.precipitation: err is not defined
23:23:16.069 [pimatic] debug: ReferenceError: err is not defined
23:23:16.069 [pimatic] debug:>    at /home/pi/weather.coffee:120:26
23:23:16.069 [pimatic] debug:>    at tryCatch1 (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:43:21)
23:23:16.069 [pimatic] debug:>    at Promise$_callHandler [as _callHandler] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:627:13)
23:23:16.069 [pimatic] debug:>    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:641:18)
23:23:16.069 [pimatic] debug:>    at Promise$_settlePromiseAt [as _settlePromiseAt] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:800:14)
23:23:16.069 [pimatic] debug:>    at Promise$_settlePromises [as _settlePromises] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:934:14)
23:23:16.069 [pimatic] debug:>    at Promise$_rejectPromises [as _rejectPromises] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:927:10)
23:23:16.069 [pimatic] debug:>    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:75:12)
23:23:16.069 [pimatic] debug:>    at Async$consumeFunctionBuffer (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:38:14)
23:23:16.069 [pimatic] debug:>    at process._tickCallback (node.js:415:13)
23:23:16.115 [pimatic] warn: Could not update variable weather.status: err is not defined
23:23:16.154 [pimatic] debug: [ReferenceError: err is not defined]
23:23:16.190 [pimatic] warn: Could not update variable weather.windspeed: err is not defined
23:23:16.229 [pimatic] debug: [ReferenceError: err is not defined]
23:23:16.266 [pimatic] warn: Could not update variable weather.temperature: err is not defined
23:23:16.304 [pimatic] debug: [ReferenceError: err is not defined]
23:23:16.340 [pimatic] warn: Could not update variable weather.humidity: err is not defined
23:23:16.376 [pimatic] debug: [ReferenceError: err is not defined]
23:23:16.414 [pimatic] warn: Could not update variable forecast.forecast: err is not defined
23:23:16.451 [pimatic] debug: [ReferenceError: err is not defined]
23:23:16.487 [pimatic] warn: Could not update variable forecast.low: err is not defined
23:23:16.528 [pimatic] debug: [ReferenceError: err is not defined]
23:23:16.564 [pimatic] warn: Could not update variable forecast.high: err is not defined
23:23:16.601 [pimatic] debug: [ReferenceError: err is not defined]
23:23:16.640 [pimatic] warn: Could not update variable forecast.precipitation: err is not defined
23:23:16.676 [pimatic] debug: [ReferenceError: err is not defined]
```

After a while the weather info is updated perfectly fine.

I configured it as follows:

```json
        {
            "class": "WeatherDevice",
            "id": "weather",
            "name": "Nu",
            "location": "Amsterdam, Netherlands",
            "degreeType": "C",
            "timeout": 300000
        },
        {
            "class": "WeatherForecastDevice",
            "id": "forecast",
            "name": "Voorspelling morgen",
            "location": "Amsterdam, Netherlands",
            "degreeType": "C",
            "timeout": 600000,
            "day": 1
        }
```

Is there anything I can do about this?

Kind regards,
Ronald

**Comment by sweetpi** [comment]
It's an error in the plugin code I introduced recently. I submitted a pull request, so it should be fixed soon.

**Comment by rovale** [comment]
Ok, I see, thanks a lot!

**Comment by josecastroleon** [comment]
Just pushed and updated the package on npm
